import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Hero from '../components/Home/Hero'
import Brands from '@/components/Home/Brands'
import Layout from '@/components/Home/Streaming/Live/Layout'
import LayoutCreatorsEvents from '@/components/Home/Streaming/Creators&Events/LayoutCreatorsEvents'
import Scores from '@/components/Home/Scores/Scores'
import LayoutStore from '@/components/Home/Store/LayoutStore'
import LayoutTeam from '@/components/Home/Team/LayoutTeam'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-full h-full overflow-x-hidden'>
     
     <Hero/>
     <Brands/>
     <Layout/>
     <LayoutCreatorsEvents/> 
     <Scores/>
     <LayoutStore/>
     <LayoutTeam/>
      </main>
    </>
  )
}
